### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by cenchaojun** [jingwu6/Extended-Agriculture-Vision-Dataset#1]
Dear Jing Wu,

I hope this message finds you well.    I am a user of your repository on GitHub, and I am very interested in your project, particularly the dataset you have provided.    However, I have encountered some difficulties in downloading the dataset from Amazon.

Therefore, I would like to make a request: would it be possible for you to consider uploading the dataset to Google Drive and providing a download link for all users interested in your project?    This would greatly facilitate access to the dataset, especially for those users who may be restricted by certain regions or network environments.

If you could accommodate my request, I would greatly appreciate it.    Of course, if you have any other convenient ways to make the dataset accessible to me and other users, I would also be very thankful for your efforts.

Thank you once again for your contribution and hard work.    I look forward to your response.

Warmest regards,
cen chaojun
from China Agricultural University

**Comment by jingwu6** [comment]
Hi Chaojun,

Thanks for reaching out.

Given the storage constraints, I'm currently not able to provide the full dataset on Google Drive. However, I have uploaded ~100GB of subset datasets to Dropbox, covering each year, at the following link:
https://www.dropbox.com/scl/fo/7yzzc8hqtvaki2y1md6h4/h?rlkey=su71dij6xfb964zfwe1d6kros&e=1&dl=0.

I'll provide the rest of it once the storage resources are available.

Thank you for your interest in the datasets and paper!
